version: "3"
services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: zen-tracking
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-network
    ports:
      - 5432:5432
    mem_limit: 1024m
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    volumes:
      - pgadmin:/root/.pgadmin
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGADMIN_DEFAULT_EMAIL: default@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - app-network
    restart: unless-stopped
    mem_limit: 206m
  zen-tracking:
    build:
      context: .
    environment:
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/zen-tracking
      DATABASE_URL_NEW: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/zen-tracking
      JWT_ACCESS_TOKEN_SECRET_KEY: ${JWT_ACCESS_TOKEN_SECRET_KEY}
      JWT_REFRESH_TOKEN_SECRET_KEY: ${JWT_REFRESH_TOKEN_SECRET_KEY}
    ports:
      - "80:4000"
    depends_on:
      - postgres
    networks:
      - app-network
    mem_limit: 2048m
  # webserver:
  #   image: nginx:mainline-alpine
  #   container_name: webserver
  #   restart: unless-stopped
  #   ports:
  #     - "80:4000"
  #   volumes:
  #     - web-root:/var/www/html
  #     - ./nginx:/etc/nginx/conf.d
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #   depends_on:
  #     - zen-tracking
  #   networks:
  #     - app-network
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #     - web-root:/var/www/html
  #   depends_on:
  #     - webserver
  #   command: certonly --webroot --webroot-path=/var/www/html --email ekku.eki@gmail.com --agree-tos --no-eff-email --staging -d zen-tracking  -d www.zen-tracking.com
networks:
  app-network:
    driver: bridge
volumes:
  postgres_data:
    driver: local
  pgadmin:
    driver: local
  # certbot-etc:
  # certbot-var:
  # web-root:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: /home/eke/zen-tracking/tmp/
  #     o: bind
