version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - './tmp:/tmp'
    environment:
      POSTGRES_DB: zen-tracking
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - postgres
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    volumes:
        - pgadmin:/root/.pgadmin
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGADMIN_DEFAULT_EMAIL: default@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
volumes:
  postgres_data:
    driver: local
  pgadmin:
    driver: local