version: "3"
services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: zen-tracking
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - app-network
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    volumes:
      - pgadmin:/root/.pgadmin
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGADMIN_DEFAULT_EMAIL: default@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - app-network
    restart: unless-stopped
  zen-tracking:
    build:
      context: .
    environment:
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_S3_REGION: eu-west-2
      AWS_S3_BUCKET_NAME: zen-tracking
      DATABASE_URL: postgresql://user:password@localhost:5432/zen-tracking
      DATABASE_URL_PROD: postgresql://xkkmohypmlwygy:1da6b32373c5c6a883f9bfc1893f4cb5d7aaf7817049fc11a373e9b379aba701@ec2-54-247-158-179.eu-west-1.compute.amazonaws.com:5432/dfek7t3voagsh9
      JWT_ACCESS_TOKEN_SECRET_KEY: awdoiuhawuidawhd
      JWT_REFRESH_TOKEN_SECRET_KEY: 329r8uh39a823jfaawef
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    networks:
      - app-network
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nodejs
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email ekku.eki@gmail.com --agree-tos --no-eff-email --staging -d zen-tracking  -d www.zen-tracking.com
networks:
  app-network:
    driver: bridge
volumes:
  postgres_data:
    driver: local
  pgadmin:
    driver: local
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/eke/zen-tracking/tmp/
      o: bind
